# Generated by Django 3.1.4 on 2020-12-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201216_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='static/images/default.jpeg', null=True, upload_to='post_image/'),
        ),
    ]
