# Generated by Django 3.1.4 on 2020-12-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201216_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='../uploads/post_image/default.jpeg', null=True, upload_to='post_image/'),
        ),
    ]
