# Generated by Django 3.1.4 on 2020-12-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201216_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='post_image/default.jpeg', upload_to='post_image/'),
        ),
    ]
