# Generated by Django 3.1.4 on 2020-12-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_comment_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
