# Generated by Django 3.1.4 on 2020-12-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20201217_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='post_image/default.jpeg', null=True, upload_to='post_image/'),
        ),
    ]
