# Generated by Django 3.1.4 on 2020-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20201218_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=None, null=True, upload_to='post_image/'),
        ),
    ]
